// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Remoting.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.Remoting {

  /// <summary>Holder for reflection information generated from Remoting.proto</summary>
  public static partial class RemotingReflection {

    #region Descriptor
    /// <summary>File descriptor for Remoting.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RemotingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5SZW1vdGluZy5wcm90bxIIUmVtb3RpbmcaDk1lc3NhZ2VzLnByb3RvMmYK",
            "B1NlcnZpY2USKwoHUmVxdWVzdBIOLk1lc3NhZ2VzLlBpbmcaDi5NZXNzYWdl",
            "cy5Qb25nIgASLgoGU3RyZWFtEg4uTWVzc2FnZXMuUGluZxoOLk1lc3NhZ2Vz",
            "LlBvbmciACgBMAFCEaoCDlByb3RvLlJlbW90aW5nYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.Messages.MessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
